### ISSUE TITLE
百度翻译报错

### ISSUE THREAD

**Issue by issmile** [SagittariusZhu/translators#1]
2022-02-24 18:34:05,225 ERROR 198660 [-/127.0.0.1/-/1025ms POST /article2word] nodejs.ReferenceError: localStorage is not defined
    at eval (eval at get_host_info (E:\uni-app\背单词v0.7.1-目标自己增加单词,富文本\后端base\node_modules\translators\lib\baidu.js:104:17), <anonymous>:35:35)
    at get_host_info (E:\uni-app\背单词v0.7.1-目标自己增加单词,富文本\后端base\node_modules\translators\lib\baidu.js:104:17)
    at baidu_api (E:\uni-app\背单词v0.7.1-目标自己增加单词,富文本\后端base\node_modules\translators\lib\baidu.js:144:29)

**Comment by SagittariusZhu** [comment]
这个情况应该是获取百度页面时出错了，但我这里无法复现这个错误。

首先你可以贴出你的运行环境，包括nodejs的版本、操作系统的版本。

其次你可以下载这个工程，然后执行`yarn test`，如果还发生这个错误，进入src/baidu.js，在第72行加上try/catch，并打印js_txt字符串，然后将字符串贴出来。

**Comment by legend80s** [comment]
运行环境，任何 node 都会，因为 localStorage 只有浏览器有
https://runkit.com/embed/8e59kl2bluy8
