### ISSUE TITLE
Error when using baiduTranslator

### ISSUE THREAD

**Issue by SteveMartin60** [SagittariusZhu/translators#2]
Both the Bing and Youdao translators successfully translate the string.

Test String: 根据区委区政府要求
```
bingTranslator  ('根据区委区政府要求', 'zh', 'en', {}).then(value => {    console.log('Bing  : ' + value);});
youdaoTranslator('根据区委区政府要求', 'zh', 'en', {}).then(value => {    console.log('YouDao: ' + value);});
baiduTranslator ('根据区委区政府要求', 'zh', 'en', {}).then(value => {    console.log('Baidu : ' + value);});

```
**Error Message:**
```
(node:13436) UnhandledPromiseRejectionWarning: ReferenceError: localStorage is not defined
    at eval (eval at get_host_info (D:\dev\chinese-temp\node_modules\translators\lib\baidu.js:104:17), <anonymous>:35:35)
    at get_host_info (D:\dev\chinese-temp\node_modules\translators\lib\baidu.js:104:17)
    at baidu_api (D:\dev\chinese-temp\node_modules\translators\lib\baidu.js:144:29)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:13436) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:13436) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by legend80s** [comment]
yes it does not work https://runkit.com/embed/8e59kl2bluy8 
@SagittariusZhu
